import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Mail,
  FileText,
  ListChecks,
  Search,
  MessageSquare,
  ArrowRight,
  Sparkles,
  ShieldAlert,
} from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "AI Workplace Productivity Assistant" },
      {
        name: "description",
        content:
          "Automate emails, meeting notes, planning, research, and chat with an AI assistant built for professionals.",
      },
    ],
  }),
  component: Dashboard,
});

const features = [
  {
    title: "Smart Email Generator",
    description: "Draft polished, on-tone emails in seconds from a few notes.",
    icon: Mail,
    href: "/email",
  },
  {
    title: "Meeting Notes Summarizer",
    description: "Turn raw notes or transcripts into decisions and action items.",
    icon: FileText,
    href: "/meetings",
  },
  {
    title: "AI Task Planner",
    description: "Break goals into prioritized milestones and a daily plan.",
    icon: ListChecks,
    href: "/tasks",
  },
  {
    title: "AI Research Assistant",
    description: "Get structured briefings on any workplace topic.",
    icon: Search,
    href: "/research",
  },
  {
    title: "AI Chatbot",
    description: "Ask anything — brainstorm, draft, or troubleshoot in chat.",
    icon: MessageSquare,
    href: "/chat",
  },
] as const;

function Dashboard() {
  return (
    <div className="mx-auto max-w-6xl px-6 py-10">
      <section
        className="overflow-hidden rounded-2xl border p-8 shadow-[var(--shadow-soft)]"
        style={{ background: "var(--gradient-subtle)" }}
      >
        <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-primary">
          <Sparkles className="h-3.5 w-3.5" /> Your AI productivity suite
        </div>
        <h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">
          Automate the busywork. Focus on the work that matters.
        </h1>
        <p className="mt-3 max-w-2xl text-sm text-muted-foreground sm:text-base">
          Five AI-powered tools to help professionals write, plan, research, and
          communicate faster — all in one clean workspace.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
          Tools
        </h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((f) => (
            <Link
              key={f.href}
              to={f.href}
              className="group flex flex-col rounded-xl border bg-card p-5 shadow-[var(--shadow-soft)] transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-[var(--shadow-elegant)]"
            >
              <div
                className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg text-primary-foreground"
                style={{ background: "var(--gradient-primary)" }}
              >
                <f.icon className="h-5 w-5" />
              </div>
              <h3 className="text-base font-semibold tracking-tight">{f.title}</h3>
              <p className="mt-1 flex-1 text-sm text-muted-foreground">{f.description}</p>
              <div className="mt-4 flex items-center gap-1 text-xs font-medium text-primary">
                Open <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
              </div>
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-10 flex items-start gap-3 rounded-xl border bg-muted/40 p-4 text-sm text-muted-foreground">
        <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
        <p>
          <span className="font-medium text-foreground">Responsible AI:</span> Outputs
          are generated by AI and may contain errors, omissions, or bias. Always review,
          edit, and verify before sending, sharing, or acting on results — especially for
          sensitive topics or decisions involving people, finances, or compliance.
        </p>
      </section>
    </div>
  );
}
