/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MyAppointmentsRouteImport } from './routes/my-appointments'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CapfinRouteImport } from './routes/capfin'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCapfinChatRouteImport } from './routes/api/capfin-chat'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAppointmentsRoute = MyAppointmentsRouteImport.update({
  id: '/my-appointments',
  path: '/my-appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CapfinRoute = CapfinRouteImport.update({
  id: '/capfin',
  path: '/capfin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapfinChatRoute = ApiCapfinChatRouteImport.update({
  id: '/api/capfin-chat',
  path: '/api/capfin-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/capfin': typeof CapfinRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
  '/api/capfin-chat': typeof ApiCapfinChatRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/capfin': typeof CapfinRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
  '/api/capfin-chat': typeof ApiCapfinChatRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/capfin': typeof CapfinRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
  '/api/capfin-chat': typeof ApiCapfinChatRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/capfin'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/my-appointments'
    | '/research'
    | '/tasks'
    | '/api/capfin-chat'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/capfin'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/my-appointments'
    | '/research'
    | '/tasks'
    | '/api/capfin-chat'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/capfin'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/my-appointments'
    | '/research'
    | '/tasks'
    | '/api/capfin-chat'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CapfinRoute: typeof CapfinRoute
  ChatRoute: typeof ChatRoute
  EmailRoute: typeof EmailRoute
  MeetingsRoute: typeof MeetingsRoute
  MyAppointmentsRoute: typeof MyAppointmentsRoute
  ResearchRoute: typeof ResearchRoute
  TasksRoute: typeof TasksRoute
  ApiCapfinChatRoute: typeof ApiCapfinChatRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-appointments': {
      id: '/my-appointments'
      path: '/my-appointments'
      fullPath: '/my-appointments'
      preLoaderRoute: typeof MyAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capfin': {
      id: '/capfin'
      path: '/capfin'
      fullPath: '/capfin'
      preLoaderRoute: typeof CapfinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capfin-chat': {
      id: '/api/capfin-chat'
      path: '/api/capfin-chat'
      fullPath: '/api/capfin-chat'
      preLoaderRoute: typeof ApiCapfinChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CapfinRoute: CapfinRoute,
  ChatRoute: ChatRoute,
  EmailRoute: EmailRoute,
  MeetingsRoute: MeetingsRoute,
  MyAppointmentsRoute: MyAppointmentsRoute,
  ResearchRoute: ResearchRoute,
  TasksRoute: TasksRoute,
  ApiCapfinChatRoute: ApiCapfinChatRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
